---
title: Analyzing Inpatient Data From the Hospital Charge Data Set
author: Pranay Aryal
date: '2017-04-28'
slug: ''
categories: []
tags: []
draft: yes
---

#### About the dataset

The dataset is [openly available](https://www.data.gov/health/). It shows the provider summary for the top 100 Diagnosis-Related Groups (DRG) for the year 2011 in the US. DRGs only capture diagnosis groups which encompass related diagnoses for ease of classification and coding. However, the details are lost with this.

####Columns in the dataset

The dataset has the following columns: 

 - DRG Definition (diagnosis)                       
 - Provider Id                         
 - Provider Name                        
 - Provider Street Address             
 - Provider City                        
 - Provider State                      
 - Provider Zip Code                    
 - Hospital Referral Region Description
 - Total Discharges                     
 - Average Covered Charges             
 - Average Total Payments               
 - Average Medicare Payments  
 
 The Average Covered Charges differs with differing providers. This will be our column of interest. Let us take a look at its histogram after converting the column to a float. We must remember diagnoses have been clubbed together to allow for easy coding and charging. However, the granularity of individual disease is lost

```{r echo=F, message=F, warning=F}
library(tidyverse)
inpatient <- read_csv('~/Downloads/inpatient.csv')
inpatient[,10:12] <- sapply(inpatient[,10:12], function(x)gsub('\\$', '', x))
inpatient[,10:12] <- sapply(inpatient[,10:12], function(x)as.numeric(x))
inpatient$`Average Covered Charges` %>% qplot

```



There seems to be a few outliers beyond the 250000 mark. Let's explore them.
The diagnosis with the highest charges is "RESPIRATORY SYSTEM DIAGNOSIS W VENTILATOR SUPPORT 96+ HOURS." The provider is Stanford Hospital, CA. This is understandable because Stanford is a teaching hospital. It is also situated in California, an expensive state. The patient required ventilator support which is an expensive treatment managed in ICU.

What are the top 5 most expensive diagnoses?

Diagnosis                                  | Average Charge
-------------------------------------------|----------------
SEPTICEMIA OR SEVERE SEPSIS W MV 96+ HOURS | $163227.33
RESPIRATORY SYSTEM DIAGNOSIS W VENTILATOR SUPPORT 96+ HOURS |  $143428.05
INFECTIOUS & PARASITIC DISEASES W O.R. PROCEDURE W MCC |  $139186.35
MAJOR SMALL & LARGE BOWEL PROCEDURES W MCC | $135330.94
PERC CARDIOVASC PROC W DRUG-ELUTING STENT W MCC OR 4+ VESSELS/STENTS  |  $96348.81


Septicemia or severe sepsis with mechanical ventilation is an expensive disease to treat. Mechanical ventilation means that a tube has been inserted a person's windpipe and a machine helps with his breathing. Understandably, this is only done in ICU and is expensive. Also the duration of the disease is unknown here because it only says 96+ Hours which could be from a week to a month or more.

Which are the providers with highest average charges?

Hospital | Average Charge (dollars)
---------|--------------------------
UVA Health Sciences Center, Charlotesville, VA | 21922.00
Bayonne Hospital Center, Bayonne, NJ | 147441 
Doctors Medical Center, Modesto, CA | 144695
Stanford Hospital, Stanford, CA | 138818
Northbay Medical Center, Fairfield, CA | 138504

Three seem to be from California, which is understandable because of high expenses in CA. Let's explore why the one from VA is expensive. VA ranks 29th among the states for average charges. This is strange. Why should one hospital from VA be so expensive? 

It turns out that there is only one entry for that hospital in the dataset and the diagnosis is "RESPIRATORY SYSTEM DIAGNOSIS W VENTILATOR SUPPORT 96+ HOURS"Let's see how the charge for this diagnosis compares with others in VA


The top 5 diagnoses for this outlier are:

 - 870  SEPTICEMIA OR SEVERE SEPSIS W MV 96+ HOURS   132
 - 329  MAJOR SMALL & LARGE BOWEL PROCEDURES W MCC   117
 - 853  INFECTIOUS & PARASITIC DISEASES W O.R. PROCEDURE W MCC   117
 - 207  RESPIRATORY SYSTEM DIAGNOSIS W VENTILATOR SUPPORT 96+ HOURS    96
 - 460  SPINAL FUSION EXCEPT CERVICAL W/O MCC    15
 

Which is the most expensive to treat overall?


Looks like septicemia is still the overall most expensive

The spinal fusion (code 460) in the outlier list is interesting because it is not there in the overall list. I don't know what it is done for. Let me google and come back.



